### PR TITLE
Introduce heartbeats for event watching

### PR DESCRIPTION
**Pull request by grobie**
In order to detect connection loss while waiting for events, this change
introduces a heartbeat (via NOP requests) continuesly exchanged with the
server.

@matthiasr @xla

### CODE REVIEW

**Comment by matthiasr** [comment]
What happens if there are multiple waits? It's just extra chatter, but I think it would be cleaner to ensure there is at most one heartbeat routine.

**Comment by grobie** [comment]
I was thinking about it, but it left it out due to the extra complexity as
our clients usually don't have more than on wait routine. I'll think about
an approach.

**Comment by matthiasr** [comment]
if we normally only have one watch, then :+1: for the simple approach.

**Comment by xla** [comment]
:+1: :shipit: :octocat: :dango:

**Comment by grobie** [comment]
I changed the implementation to have one heartbeat routine per connection instead.

**Pull request merged**
